apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonRepositoryInstall
metadata:
  name: keda-repo-install
  namespace: vmware-system-vks-public
spec:
  addonRepositoryRef:
    name: keda-repo
    namespace: vmware-system-vks-public
